// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_consistency_constant
double get_consistency_constant(int n, std::string method);
RcppExport SEXP _robustscale_get_consistency_constant(SEXP nSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(get_consistency_constant(n, method));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_ensemble
double cpp_scale_ensemble(NumericVector x, int n_boot);
RcppExport SEXP _robustscale_cpp_scale_ensemble(SEXP xSEXP, SEXP n_bootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_ensemble(x, n_boot));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_gmd
double cpp_scale_gmd(NumericVector x);
RcppExport SEXP _robustscale_cpp_scale_gmd(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_gmd(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_mad
double cpp_scale_mad(NumericVector x);
RcppExport SEXP _robustscale_cpp_scale_mad(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_mad(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_iqr
double cpp_scale_iqr(NumericVector x);
RcppExport SEXP _robustscale_cpp_scale_iqr(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_iqr(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_sn
double cpp_scale_sn(NumericVector x);
RcppExport SEXP _robustscale_cpp_scale_sn(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_sn(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_qn
double cpp_scale_qn(NumericVector x);
RcppExport SEXP _robustscale_cpp_scale_qn(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_qn(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_sd_c4
double cpp_scale_sd_c4(NumericVector x);
RcppExport SEXP _robustscale_cpp_scale_sd_c4(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_sd_c4(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robustscale_get_consistency_constant", (DL_FUNC) &_robustscale_get_consistency_constant, 2},
    {"_robustscale_cpp_scale_ensemble", (DL_FUNC) &_robustscale_cpp_scale_ensemble, 2},
    {"_robustscale_cpp_scale_gmd", (DL_FUNC) &_robustscale_cpp_scale_gmd, 1},
    {"_robustscale_cpp_scale_mad", (DL_FUNC) &_robustscale_cpp_scale_mad, 1},
    {"_robustscale_cpp_scale_iqr", (DL_FUNC) &_robustscale_cpp_scale_iqr, 1},
    {"_robustscale_cpp_scale_sn", (DL_FUNC) &_robustscale_cpp_scale_sn, 1},
    {"_robustscale_cpp_scale_qn", (DL_FUNC) &_robustscale_cpp_scale_qn, 1},
    {"_robustscale_cpp_scale_sd_c4", (DL_FUNC) &_robustscale_cpp_scale_sd_c4, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_robustscale(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
