# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_consistency_constant <- function(n, method) {
    .Call(`_robustscale_get_consistency_constant`, n, method)
}

cpp_scale_ensemble <- function(x, n_boot) {
    .Call(`_robustscale_cpp_scale_ensemble`, x, n_boot)
}

cpp_scale_gmd <- function(x) {
    .Call(`_robustscale_cpp_scale_gmd`, x)
}

cpp_scale_mad <- function(x) {
    .Call(`_robustscale_cpp_scale_mad`, x)
}

cpp_scale_iqr <- function(x) {
    .Call(`_robustscale_cpp_scale_iqr`, x)
}

cpp_scale_sn <- function(x) {
    .Call(`_robustscale_cpp_scale_sn`, x)
}

cpp_scale_qn <- function(x) {
    .Call(`_robustscale_cpp_scale_qn`, x)
}

cpp_scale_sd_c4 <- function(x) {
    .Call(`_robustscale_cpp_scale_sd_c4`, x)
}

